---
swagger: "2.0"
info:
  description: "Simple REST API to locate hyperlinks in a single supplied URL"
  version: "v1"
  title: "Web Link Scraper"
host: "virtserver.swaggerhub.com"
basePath: "/seanprince/Web-Link-Scraper/1"
tags:
- name: "Links"
schemes:
- "https"
- "http"
paths:
  /links:
    get:
      tags:
      - "Links"
      summary: "Locate hyperlinks on page identified by URL"
      description: "Locate all the hyperlinks present on the page identified by a\
        \ single input URL\n"
      produces:
      - "application/json"
      parameters:
      - name: "url"
        in: "query"
        description: "URL of page to scrape"
        required: false
        type: "string"
      responses:
        200:
          description: "Success - hyperlinks are returned."
          schema:
            $ref: "#/definitions/LinksResponse"
        400:
          description: "Bad request"
          schema:
            $ref: "#/definitions/ErrorResponse"
definitions:
  NameValuePair:
    type: "object"
    required:
    - "name"
    - "value"
    properties:
      name:
        type: "string"
        description: "Name of the item"
      value:
        type: "string"
        description: "Value of the item"
  Hyperlink:
    type: "object"
    properties:
      linkUrl:
        type: "string"
        example: "http://www.bbc.com/news"
        description: "URL of hyperlink"
      cssSelector:
        type: "string"
        example: "html > body > p:nth-child(1) > a"
        description: "CSS selector that locates URL in document"
    example:
      linkUrl: "http://www.bbc.com/news"
      cssSelector: "html > body > p:nth-child(1) > a"
  LinksResponse:
    type: "object"
    properties:
      links:
        type: "array"
        description: "Array of all hyperlinks scraped from input page. Multiple hyperlinks\
          \ are returned if the same URL link appears in multiple locations on the\
          \ page."
        items:
          $ref: "#/definitions/Hyperlink"
    example:
      links:
      - linkUrl: "http://www.bbc.com/news"
        cssSelector: "html > body > p:nth-child(1) > a"
      - linkUrl: "http://www.bbc.com/news"
        cssSelector: "html > body > p:nth-child(1) > a"
  ErrorResponse:
    type: "object"
    required:
    - "status"
    - "title"
    - "type"
    properties:
      type:
        type: "string"
        example: "v1/links/problems/bad-format"
        description: "A URI that indicates the reason for the error."
      title:
        type: "string"
        example: "Bad request."
        description: "Short, localised, human-readable summary of the problem."
      status:
        type: "string"
        example: "4xx"
        description: "The HTTP status code generated by the origin server.\nIt is\
          \ included here because the HTTP status code might be changed by proxies,\
          \ etc. \n"
      detail:
        type: "string"
        example: "The mandatory property [name] was not included in the supplied definition."
        description: "A human-readable explanation of the problem, not localised.\
          \ \nPrimarily intended for developers who need to debug the problem\n"
      instance:
        type: "string"
        description: "Optional URI that identifies the specific occurrence of the\
          \ problem."
      additionalData:
        type: "array"
        description: "Collection of name-value pairs. Populated only for certain types\
          \ of error."
        items:
          $ref: "#/definitions/NameValuePair"
